"""Добавил модели

Revision ID: 24d81ba2cfcd
Revises: 62840d97125c
Create Date: 2025-11-15 14:48:01.884031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24d81ba2cfcd'
down_revision: Union[str, Sequence[str], None] = '62840d97125c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dialogs', sa.Column('list_messages', sa.ARRAY(sa.JSON()), nullable=True))
    op.drop_column('dialogs', 'dialog')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dialogs', sa.Column('dialog', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('dialogs', 'list_messages')
    # ### end Alembic commands ###
