"""обновил Dialogs

Revision ID: cd38d06f1003
Revises: 24d81ba2cfcd
Create Date: 2025-11-15 15:36:40.568408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd38d06f1003'
down_revision: Union[str, Sequence[str], None] = '24d81ba2cfcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dialogs', sa.Column('username', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dialogs', 'username')
    # ### end Alembic commands ###
